let ratio_phrases = [
  "don’t care",
  "didn’t ask",
  "cry about it",
  "who asked",
  "stay mad",
  "get real",
  "bleed",
  "mald seethe cope harder",
  "dilate",
  "incorrect",
  "hoes mad",
  "pound sand",
  "basic skill issue",
  "typo",
  "ur dad left",
  "you fell off",
  "no u",
  "the audacity",
  "triggered",
  "repelled",
  "ur a minor",
  "k.",
  "any askers",
  "get a life",
  "ok and?",
  "cringe",
  "copium",
  "go outside",
  "touch grass",
  "kick rocks",
  "quote tweet",
  "think again",
  "not based",
  "not funny didn’t laugh",
  "social credits -999, 999, 999, 999",
  "get good",
  "reported",
  "ad hominem",
  "ok boomer",
  "small pp",
  "ur allergic to sunlight",
  "GG!",
  "get rekt",
  "trolled",
  "your loss",
  "muted",
  "banned",
  "kicked",
  "permaban",
  "useless",
  "i slept with ur mom",
  "yo momma",
  "yo momma so fat",
  "redpilled",
  "no bitches allowed",
  "i said it better",
  "tiktok fan",
  "get a life",
  "unsubscribed",
  "plundered",
  "go tell reddit",
  "donowalled",
  "simp",
  "get sticked bug LOL",
  "talk nonsense",
  "trump supporter",
  "your’re a full time discord mod",
  "you’re*",
  "grammar issue",
  "nerd",
  "get clapped",
  "kys",
  "lorem ipsum dolor sit amet",
  "go outside",
  "bleach",
  "lol",
  "gay",
  "retard",
  "autistic",
  "reported",
  "ask deez",
  "ez clap",
  "straight cash",
  "idgaf",
  "ratio again",
  "stay mad",
  "read FAQ",
  "youre lost",
  "you “re”",
  "stay pressed",
  "reverse double take back",
  "pedophile",
  "cancelled",
  "done for",
  "don't give a damn",
  "get a job",
  "sus",
  "baka",
  "sussy baka",
  "get blocked",
  "mad free",
  "freer than air",
  "furry",
  "rip bozo",
  "you're a (insert stereotype)",
  "slight_smile",
  "aired",
  "cringe again",
  "Super Idol的笑容",
  "mad cuz bad",
  "my pronouns are xe, xem & xyr",
  "irrelevant",
  "deal with it",
  "screencapped your bio",
  "karen/kyle",
  "jealous",
  "you're deaf",
  "balls",
  "i'll be right back",
  "go ahead whine about it",
  "not straight",
  "eat paper",
  "you lose",
  "count to three",
  "your problem",
  "no one cares",
  "log off",
  "don't care even more",
  "sex offender",
  "sex defender",
  "get religion",
  "not okay",
  "glhf",
  "NFT owner",
  "you make bad memes",
  "problematic",
  "fall in line",
  "dog water",
  "you look like a wall",
  "you don’t know 2",
  "2 with yo head ass",
  "you are going to my cringe compilation",
  "you can’t count to five",
  "try again",
  "you failed kindergarten",
  "rickrolled",
  "no lifer",
  "guten freunden schickt man einen deutschen panzer",
  "you have a anime profile picture",
  "an*",
  "fatherless",
  "motherless",
  "sisterless",
  "brotherless",
  "orphan",
  "you can't catch this ratio",
  "catch some bitches",
  "I don't care about your opinion",
  "genshin player",
  "you dress like garbage",
  "日本語がお上手ですね",
  "get fucked",
  "you can’t understand what the word intelligence means with your dumb ass",
  "you have hair",
  "queued",
  "put some thought into what you're going to do with that",
  "stfu",
  "go to bed",
  "yes, i'm taller than you",
  "i think your joke is funny",
  "i rejected your mother's advances",
  "marooned",
  "you can’t read",
  "I win",
  "final rati",
  "Don’t care",
  "didn’t ask",
  "cry about it",
  "stay mad",
  "get real",
  "L",
  "mald seethe cope harder",
  "ho mad",
  "basic",
  "skill issue",
  "ratio",
  "you fell off",
  "the audacity",
  "triggered",
  "any askers",
  "repelled",
  "get a life",
  "ok",
  "and?",
  "cringe",
  "touch grass",
  "donowalled",
  "not based",
  "your a (insert stereotype)",
  "not funny didn’t laugh",
  "you “re”",
  "grammar issues",
  "go outside",
  "get good",
  "reported",
  "ad hominem",
  "GG!",
  "ask deez",
  "ez clap",
  "straight cash",
  "ratio agian",
  "final ratio",
  "problemati",
  "cope",
  "don’t care",
  "didn’t ask",
  "cry about it",
  "stay mad",
  "get real",
  "L",
  "mald seethe cope harder",
  "h0es mad",
  "basic",
  "skill issue",
  "ratio",
  "you fell off",
  "the audacity",
  "triggered",
  "any askers",
  "redpilled",
  "get a life",
  "ok and?",
  "cringe",
  "touch grass",
  "donowalled",
  "not based",
  "your’re probably white",
  "not funny didn’t laugh",
  "you’re*",
  "grammar issue",
  "go outside",
  "get good",
  "reported",
  "ad hominem",
  "GG!",
  "ur momdon’t care",
  "didn’t ask",
  "cry about it",
  "stay mad",
  "get real",
  "L",
  "mald seethe cope harder",
  "hoes mad",
  "basic",
  "skill issue",
  "ratio",
  "you fell off",
  "the audacity",
  "triggered",
  "any askers",
  "redpilled",
  "get a life",
  "ok and?",
  "cringe",
  "touch grass",
  "donowalled",
  "not based",
  "your’re a full time discordian",
  "not funny didn’t laugh",
  "you’re*",
  "grammar issue",
  "go outside",
  "get good",
  "your gay",
  "reported",
  "ad hominem",
  "GG!",
  "ur mom",
  "unknown",
  "random",
  "biased",
  "racially motivated",
  "kys",
  "ur unfunny",
  "ratio don’t care",
  "didn’t ask",
  "cry about it"
];

let ratio_count_input = document.getElementById("ratio-count");
let generate_button = document.getElementById("generate");
let ratio_field = document.getElementById("ratio-field");

generate_button.addEventListener("click", () => {
  let word_count = parseInt(ratio_count_input.value);
  if (word_count <= 0)
    return;  
  if(word_count >= ratio_phrases.length){
    alert("can only add " + ratio_phrases.length.toString() + " ratio phrases.");
    return;
  }
  let ratio_scentece = "L + ";
  let ratio_indexes = [];
  for(let i = 0; i < word_count; i++){
    let random_index = Math.floor(Math.random() * ratio_phrases.length);
    while(ratio_indexes.indexOf(random_index) != -1)  
      random_index = Math.random() * ratio_phrases.length;
    ratio_indexes.push(random_index);
  }
  for(let i = 0; i < word_count; i++){
    let index = ratio_indexes[i];
    if(i == word_count-1) ratio_scentece += ratio_phrases[index] + ".";
    else ratio_scentece += ratio_phrases[index] + " + ";
  }
  ratio_field.innerText = ratio_scentece;
});
